default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: db
  username: user
  password: root

development:
  <<: *default
  database: toy_development

test:
  <<: *default
  database: toy_test